# Generated by Django 2.0.1 on 2018-01-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='game_id',
            field=models.CharField(blank=True, default='b8e49e', max_length=6, unique=True),
        ),
    ]
