# Generated by Django 2.0.1 on 2018-01-13 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20180113_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Lobby')),
            ],
        ),
        migrations.AddField(
            model_name='lobby',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lobby_host', to='game.Player'),
        ),
    ]
