# Generated by Django 2.0.1 on 2018-01-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20180114_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
