# Generated by Django 2.0.1 on 2018-01-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20180114_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='night',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lobby',
            name='time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='alive',
            field=models.BooleanField(default=True),
        ),
    ]
