# Generated by Django 2.0.1 on 2018-01-20 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_remove_lobby_night'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='vote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.Player'),
        ),
    ]
