# Generated by Django 2.0.1 on 2018-01-21 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_player_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[(0, 'Bauer'), (1, 'Werwolf'), (2, 'Hexe')], default=0, max_length=32),
        ),
        migrations.AlterField(
            model_name='player',
            name='vote',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voters', to='game.Player'),
        ),
    ]
