# Generated by Django 2.0.1 on 2018-01-21 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20180121_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.IntegerField(),
        ),
    ]
