# Generated by Django 2.0.1 on 2018-01-21 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_auto_20180121_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='heal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.IntegerField(default=0),
        ),
    ]
