# Generated by Django 2.0.1 on 2018-01-21 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_auto_20180121_0252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='vote',
            new_name='vote_target',
        ),
        migrations.AddField(
            model_name='player',
            name='heal_target',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='healers', to='game.Player'),
        ),
        migrations.AddField(
            model_name='player',
            name='kill_target',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='killers', to='game.Player'),
        ),
    ]
