# Generated by Django 2.0.1 on 2018-01-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_auto_20180121_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='winning_team',
            field=models.IntegerField(default=0),
        ),
    ]
