# Generated by Django 2.0.1 on 2018-01-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_lobby_winning_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='werewolf_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lobby',
            name='witch_count',
            field=models.IntegerField(default=0),
        ),
    ]
