# Generated by Django 2.0.1 on 2018-01-30 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_lobby_time_per_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='lobby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.Lobby'),
        ),
    ]
